// Generated by Copilot
import { LRUCache } from 'lru-cache';

declare module 'lru-cache' {
    interface LRUCache<K, V, FC> {
        // Override problematic methods with compatible signatures
        entries(): IterableIterator<[K, V]>;
        keys(): IterableIterator<K>;
        values(): IterableIterator<V>;
        [Symbol.iterator](): IterableIterator<[K, V]>;
        forEach(callbackfn: (value: V, key: K, map: Map<K, V>) => void, thisArg?: any): void;
    }
}
