// Generated by Copilot
const fs = require('fs');
const path = require('path');

// Define source and destination directories
const srcDir = path.join(__dirname, '..', 'src', 'webview');
const outDir = path.join(__dirname, '..', 'out', 'webview');

// Create the output directory if it doesn't exist
if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
}

// Copy all files from src/webview to out/webview
fs.readdirSync(srcDir).forEach(file => {
    const srcPath = path.join(srcDir, file);
    const destPath = path.join(outDir, file);

    fs.copyFileSync(srcPath, destPath);
    console.log(`Copied ${file} to ${path.relative(process.cwd(), destPath)}`);
});
