// Generated by Copilot
import * as vscode from 'vscode';
import { logger } from './extension';
import { Logger } from '@timheuer/vscode-ext-logger';
import * as fs from 'fs';
import * as xml2js from 'xml2js';
import * as path from 'path';

interface TrxViewerContext {
    extensionUri?: vscode.Uri;
    cssUri?: vscode.Uri;
    scriptUri?: vscode.Uri;
    vscodeElementsCssUri?: vscode.Uri;
    codiconsUri?: vscode.Uri;
}

// This flag is used to export private functions for testing
const isTestEnv = process.env.NODE_ENV === 'test';

/**
 * View a TRX file in a webview panel
 */
export async function viewTrxFile(
    uri: vscode.Uri,
    context: TrxViewerContext,
    existingPanel?: vscode.WebviewPanel
): Promise<void> {
    logger.info('Opening TRX file', uri.fsPath);
    try {
        // Verify file exists
        try {
            await vscode.workspace.fs.stat(uri);
            logger.debug('TRX file exists', uri.fsPath);
        } catch (error) {
            logger.error('TRX file not found', error);
            throw new Error(`File not found: ${uri.fsPath}`);
        }

        // Read and validate TRX file content
        const trxContent = await fs.promises.readFile(uri.fsPath, 'utf-8');
        logger.debug('Read TRX file content', trxContent.length);
        if (!trxContent.includes('<TestRun')) {
            logger.error('Invalid TRX file: Missing TestRun element', uri.fsPath);
            throw new Error('Invalid TRX file: Missing TestRun element');
        }

        // Create or reuse the webview panel
        const panel = existingPanel || vscode.window.createWebviewPanel(
            'trxViewer',
            `TRX Viewer: ${path.basename(uri.fsPath)}`,
            vscode.ViewColumn.Beside,
            {
                enableScripts: true,
                retainContextWhenHidden: true,
                localResourceRoots: context.extensionUri ? [
                    context.extensionUri,
                    vscode.Uri.joinPath(context.extensionUri, 'node_modules', '@vscode')
                ] : []
            }
        );
        logger.debug('Webview panel created or reused');

        // Get the codicons URI
        const codiconsUri = panel.webview.asWebviewUri(
            vscode.Uri.joinPath(context.extensionUri!, 'node_modules', '@vscode', 'codicons', 'dist', 'codicon.css')
        );

        // Get paths to resources
        const webviewPath = path.join(context.extensionUri?.fsPath || '', 'out', 'webview');
        const cssUri = panel.webview.asWebviewUri(vscode.Uri.file(path.join(webviewPath, 'styles.css')));
        const vscodeElementsCssUri = panel.webview.asWebviewUri(vscode.Uri.file(path.join(webviewPath, 'vscode-elements.css')));
        const scriptUri = panel.webview.asWebviewUri(vscode.Uri.file(path.join(webviewPath, 'script.js')));
        const chartsUri = panel.webview.asWebviewUri(vscode.Uri.file(path.join(webviewPath, 'highcharts.js')));
        const templatePath = path.join(webviewPath, 'template.html');

        // Parse and render TRX content
        const trxData = await parseTrxContent(trxContent, uri.fsPath, logger);
        logger.debug('Parsed TRX content');
        const templateContent = await fs.promises.readFile(templatePath, 'utf-8');
        logger.debug('Read template content');
        const htmlContent = generateHtmlContent(templateContent, trxData, { cssUri, scriptUri, vscodeElementsCssUri, codiconsUri, chartsUri });
        panel.webview.html = htmlContent;
        logger.info('TRX file rendered in webview');

        // Handle webview messages
        panel.webview.onDidReceiveMessage(
            message => {
                switch (message.command) {
                    case 'error':
                        logger.error('Webview error message', message.text);
                        vscode.window.showErrorMessage(message.text);
                        return;
                    case 'info':
                        logger.info('Webview info message', message.text);
                        vscode.window.showInformationMessage(message.text);
                        return;
                    case 'openFile':
                        const filePath = message.filePath;
                        if (filePath && fs.existsSync(filePath)) {
                            logger.info('Opening file from webview', filePath);
                            vscode.commands.executeCommand('vscode.open', vscode.Uri.file(filePath));
                        } else {
                            logger.error('File not found', filePath);
                            vscode.window.showErrorMessage(`File not found: ${filePath}`);
                        }
                        return;
                }
            },
            undefined,
            context.extensionUri ? [] : undefined
        );

    } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);
        logger.error('Error opening TRX file', errorMessage);
        // Always call showErrorMessage immediately for testability
        const showPromise = vscode.window.showErrorMessage(`Error opening TRX file: ${errorMessage}`, 'Show Details');
        if (showPromise && typeof showPromise.then === 'function') {
            showPromise.then(selection => {
                if (selection === 'Show Details') {
                    vscode.window.showErrorMessage(`Detailed error: ${errorMessage}\nFile: ${uri.fsPath}`, { modal: true });
                }
            });
        }
        throw error;
    }
}

/**
 * Parse TRX content into a structured object
 */
async function parseTrxContent(content: string, trxFilePath: string, logger?: Logger): Promise<any> {
    try {
        const parser = new xml2js.Parser({ explicitArray: false });
        return new Promise((resolve, reject) => {
            parser.parseString(content, (err: Error | null, result: any) => {
                if (err) {
                    logger?.error('Failed to parse TRX XML', err);
                    reject(new Error(`Failed to parse TRX XML: ${err.message}`));
                } else {
                    logger?.debug('TRX XML parsed successfully');
                    resolve(normalizeTrxData(result, trxFilePath, logger));
                }
            });
        });
    } catch (error) {
        logger?.error('Failed to parse TRX file', error);
        throw new Error(`Failed to parse TRX file: ${error instanceof Error ? error.message : String(error)}`);
    }
}

/**
 * Normalize and extract important data from the TRX structure
 */
function normalizeTrxData(data: any, trxFilePath: string, logger?: Logger): any {
    const testRun = data.TestRun;
    if (!testRun) {
        logger?.error('Invalid TRX format: TestRun element not found');
        throw new Error('Invalid TRX format: TestRun element not found');
    }

    // Extract deployment root for resolving relative paths
    const trxDirectory = path.dirname(trxFilePath);
    const deploymentRoot = testRun.TestSettings?.Deployment?.$.runDeploymentRoot || '';

    const results = {
        testRun: {
            name: testRun.$.name || 'Unknown',
            runUser: testRun.$.runUser || 'Unknown',
            times: {
                start: testRun.Times?.$.start || '',
                finish: testRun.Times?.$.finish || ''
            },
            counters: extractCounters(testRun.ResultSummary?.Counters)
        },
        testDefinitions: extractTestDefinitions(testRun.TestDefinitions),
        testResults: extractTestResults(testRun.Results, trxDirectory, deploymentRoot, logger)
    };

    // Link test results with their definitions
    results.testResults = linkTestResultsWithDefinitions(results.testResults, results.testDefinitions);

    logger?.debug('Normalized TRX data');

    return results;
}

/**
 * Extract test counters from TRX data
 */
function extractCounters(counters: any): any {
    if (!counters || !counters.$) {
        return {
            total: '0',
            executed: '0',
            passed: '0',
            failed: '0',
            error: '0',
            timeout: '0',
            aborted: '0',
            inconclusive: '0',
            notExecuted: '0'
        };
    }

    return {
        total: counters.$.total || '0',
        executed: counters.$.executed || '0',
        passed: counters.$.passed || '0',
        failed: counters.$.failed || '0',
        error: counters.$.error || '0',
        timeout: counters.$.timeout || '0',
        aborted: counters.$.aborted || '0',
        inconclusive: counters.$.inconclusive || '0',
        passedButRunAborted: counters.$.passedButRunAborted || '0',
        notRunnable: counters.$.notRunnable || '0',
        notExecuted: counters.$.notExecuted || '0',
        disconnected: counters.$.disconnected || '0',
        warning: counters.$.warning || '0',
        completed: counters.$.completed || '0',
        inProgress: counters.$.inProgress || '0',
        pending: counters.$.pending || '0'
    };
}

/**
 * Extract test definitions from TRX data
 */
function extractTestDefinitions(testDefs: any): any[] {
    const definitions = [];
    if (!testDefs || !testDefs.UnitTest) {
        return [];
    }

    const unitTests = Array.isArray(testDefs.UnitTest)
        ? testDefs.UnitTest
        : [testDefs.UnitTest];

    for (const test of unitTests) {
        definitions.push({
            id: test.$.id || '',
            name: test.$.name || '',
            storage: test.TestMethod?.$.codeBase || '',
            className: test.TestMethod?.$.className || ''
        });
    }

    return definitions;
}

/**
 * Check if a file path is a supported image type
 */
function isImageFile(filePath: string): boolean {
    const imageExtensions = ['.png', '.jpg', '.jpeg', '.gif', '.webp'];
    const ext = path.extname(filePath).toLowerCase();
    return imageExtensions.includes(ext);
}

/**
 * Get MIME type for image file
 */
function getImageMimeType(filePath: string): string {
    const ext = path.extname(filePath).toLowerCase();
    const mimeTypes: { [key: string]: string } = {
        '.png': 'image/png',
        '.jpg': 'image/jpeg',
        '.jpeg': 'image/jpeg',
        '.gif': 'image/gif',
        '.webp': 'image/webp'
    };
    return mimeTypes[ext] || 'application/octet-stream';
}

/**
 * Read file and convert to base64 data URI
 */
function readFileAsBase64(filePath: string): string | null {
    try {
        if (!fs.existsSync(filePath)) {
            return null;
        }
        const fileBuffer = fs.readFileSync(filePath);
        const mimeType = getImageMimeType(filePath);
        const base64 = fileBuffer.toString('base64');
        return `data:${mimeType};base64,${base64}`;
    } catch (error) {
        return null;
    }
}

/**
 * Resolve a ResultFile path to an absolute path
 * Tries multiple strategies since TRX files can have different path conventions
 */
function resolveResultFilePath(
    resultFilePath: string,
    trxDirectory: string,
    deploymentRoot: string,
    relativeResultsDirectory?: string,
    computerName?: string
): string {
    // If already absolute, return as-is
    if (path.isAbsolute(resultFilePath)) {
        return resultFilePath;
    }

    const fileName = path.basename(resultFilePath);
    const pathSegments = resultFilePath.split(/[\\/]/);
    const firstSegment = pathSegments[0];

    // Strategy 1: Try with deployment root as-is
    if (deploymentRoot) {
        const withDeploymentRoot = path.join(trxDirectory, deploymentRoot, resultFilePath);
        if (fs.existsSync(withDeploymentRoot)) {
            return withDeploymentRoot;
        }
    }

    // Strategy 2: Try deploymentRoot\In\relativeResultsDirectory\resultFilePath
    // This is the common pattern for .NET test results with attachments
    if (relativeResultsDirectory && deploymentRoot) {
        const withInFolder = path.join(trxDirectory, deploymentRoot, 'In', relativeResultsDirectory, resultFilePath);
        if (fs.existsSync(withInFolder)) {
            return withInFolder;
        }
    }

    // Strategy 3: If first segment matches computerName, try replacing with relativeResultsDirectory
    // This handles cases where TRX uses computerName but actual folder uses execution ID
    if (relativeResultsDirectory && computerName && firstSegment === computerName) {
        const remainingPath = pathSegments.slice(1).join(path.sep);
        const pathWithExecutionId = remainingPath
            ? path.join(trxDirectory, deploymentRoot || '', relativeResultsDirectory, remainingPath)
            : path.join(trxDirectory, deploymentRoot || '', relativeResultsDirectory, fileName);
        if (fs.existsSync(pathWithExecutionId)) {
            return pathWithExecutionId;
        }

        // Also try with In folder
        const pathWithInAndExecutionId = remainingPath
            ? path.join(trxDirectory, deploymentRoot || '', 'In', relativeResultsDirectory, remainingPath)
            : path.join(trxDirectory, deploymentRoot || '', 'In', relativeResultsDirectory, fileName);
        if (fs.existsSync(pathWithInAndExecutionId)) {
            return pathWithInAndExecutionId;
        }
    }

    // Strategy 4: Try just the filename in the relativeResultsDirectory
    if (relativeResultsDirectory && deploymentRoot) {
        const inExecutionDir = path.join(trxDirectory, deploymentRoot, relativeResultsDirectory, fileName);
        if (fs.existsSync(inExecutionDir)) {
            return inExecutionDir;
        }

        // Also with In folder
        const inExecutionDirWithIn = path.join(trxDirectory, deploymentRoot, 'In', relativeResultsDirectory, fileName);
        if (fs.existsSync(inExecutionDirWithIn)) {
            return inExecutionDirWithIn;
        }
    }

    // Strategy 5: Try relative to TRX directory directly
    const relativePath = path.join(trxDirectory, resultFilePath);
    if (fs.existsSync(relativePath)) {
        return relativePath;
    }

    // Strategy 6: Try just filename in deployment root
    if (deploymentRoot) {
        const inDeploymentRoot = path.join(trxDirectory, deploymentRoot, fileName);
        if (fs.existsSync(inDeploymentRoot)) {
            return inDeploymentRoot;
        }
    }

    // Return best guess path (try with In folder pattern first as that's most common)
    if (deploymentRoot && relativeResultsDirectory) {
        return path.join(trxDirectory, deploymentRoot, 'In', relativeResultsDirectory, resultFilePath);
    }
    if (deploymentRoot) {
        return path.join(trxDirectory, deploymentRoot, resultFilePath);
    }

    return relativePath;
}

/**
 * Extract test results from TRX data
 */
function extractTestResults(results: any, trxDirectory: string = '', deploymentRoot: string = '', logger?: Logger): any[] {
    const testResults = [];
    if (!results || !results.UnitTestResult) {
        return [];
    }

    const unitResults = Array.isArray(results.UnitTestResult)
        ? results.UnitTestResult
        : [results.UnitTestResult];

    for (const result of unitResults) {
        let errorInfo = null;
        if (result.Output?.ErrorInfo) {
            errorInfo = {
                message: result.Output.ErrorInfo.Message || '',
                stackTrace: result.Output.ErrorInfo.StackTrace || ''
            };
        }

        let output = null;
        if (result.Output?.StdOut) {
            output = result.Output.StdOut;
        }

        // Extract ResultFiles and resolve paths
        // Note: ResultFiles is a sibling of Output, not a child
        let resultFiles: string[] = [];
        const relativeResultsDir = result.$.relativeResultsDirectory || '';
        const computerName = result.$.computerName || '';

        // Debug logging for ResultFiles parsing
        logger?.info('Processing test:', result.$.testName || result.$.testId, 'hasResultFiles:', !!result.ResultFiles);
        if (result.ResultFiles) {
            logger?.info('ResultFiles found:', JSON.stringify(result.ResultFiles));
        }

        if (result.ResultFiles?.ResultFile) {
            const files = Array.isArray(result.ResultFiles.ResultFile)
                ? result.ResultFiles.ResultFile
                : [result.ResultFiles.ResultFile];
            logger?.info('Parsed files array:', JSON.stringify(files));
            resultFiles = files.map((f: any) => {
                // Handle both { $: { path: '...' } } and { path: '...' } formats
                let filePath = '';
                if (f.$ && f.$.path) {
                    filePath = f.$.path;
                } else if (typeof f === 'string') {
                    filePath = f;
                } else if (f.path) {
                    filePath = f.path;
                }
                logger?.info('Extracted filePath:', filePath);
                // Resolve relative paths with all available context
                if (filePath && trxDirectory) {
                    const resolvedPath = resolveResultFilePath(
                        filePath,
                        trxDirectory,
                        deploymentRoot,
                        relativeResultsDir,
                        computerName
                    );
                    logger?.info('Resolved path:', resolvedPath, 'exists:', fs.existsSync(resolvedPath));
                    filePath = resolvedPath;
                }
                return filePath;
            }).filter((p: string) => p !== '');
            logger?.info('Final resultFiles for test:', resultFiles);
        }

        testResults.push({
            testId: result.$.testId || '',
            outcome: result.$.outcome || '',
            duration: result.$.duration || '',
            startTime: result.$.startTime || '',
            endTime: result.$.endTime || '',
            errorInfo,
            output,
            resultFiles
        });
    }

    return testResults;
}

/**
 * Link test results with their test definitions
 */
function linkTestResultsWithDefinitions(results: any[], definitions: any[]): any[] {
    return results.map(result => {
        const testDef = definitions.find(def => def.id === result.testId);
        return {
            ...result,
            name: testDef ? testDef.name : 'Unknown Test',
            className: testDef ? testDef.className : ''
        };
    });
}

/**
 * Format date string from TRX format to a more readable format
 */
function formatDate(dateStr: string): string {
    if (!dateStr) { return 'N/A'; }
    try {
        const date = new Date(dateStr);
        return date.toLocaleString();
    } catch (e) {
        return dateStr;
    }
}

interface HtmlResources {
    cssUri: vscode.Uri;
    scriptUri: vscode.Uri;
    vscodeElementsCssUri: vscode.Uri;
    codiconsUri: vscode.Uri;
    chartsUri: vscode.Uri;
}

/**
 * Generate HTML content by applying data to template
 */
function generateHtmlContent(template: string, data: any, resources: HtmlResources): string {
    const totalTests = parseInt(data.testRun.counters.total) || 0;
    const passedTests = parseInt(data.testRun.counters.passed) || 0;
    const failedTests = data.testResults.filter((t: any) => t.outcome === 'Failed');
    const passedTestResults = data.testResults.filter((t: any) => t.outcome === 'Passed');
    const skippedTestResults = data.testResults.filter((t: any) => t.outcome === 'NotExecuted');
    const otherTestResults = data.testResults.filter((t: any) =>
        t.outcome !== 'Passed' && t.outcome !== 'Failed' && t.outcome !== 'NotExecuted');
    const passPercentage = totalTests > 0 ? ((passedTests / totalTests) * 100).toFixed(2) : '0';

    // Add formatted dates to the template data
    const templateData = {
        ...data,
        testRun: {
            ...data.testRun,
            times: {
                ...data.testRun.times,
                startFormatted: formatDate(data.testRun.times.start),
                finishFormatted: formatDate(data.testRun.times.finish)
            }
        },
        passPercentage,
        failedCount: failedTests.length,
        passedCount: passedTestResults.length,
        skippedCount: skippedTestResults.length,
        otherCount: otherTestResults.length,
        failedTests: generateTestList(failedTests),
        passedTests: generateTestList(passedTestResults),
        skippedTests: generateTestList(skippedTestResults),
        otherTests: generateTestList(otherTestResults)
    };

    // Replace resource URIs and data placeholders
    let html = template
        .replace('{{cssUri}}', resources.cssUri.toString())
        .replace('{{scriptUri}}', resources.scriptUri.toString())
        .replace('{{vscodeElementsCssUri}}', resources.vscodeElementsCssUri.toString())
        .replace('{{codiconsUri}}', resources.codiconsUri.toString())
        .replace('{{chartsUri}}', resources.chartsUri.toString());

    // Replace all other template variables
    html = html.replace(/\{\{([^}]+)\}\}/g, (match, key) => {
        const value = key.split('.').reduce((obj: any, k: string) => obj?.[k], templateData);
        return value ?? '';
    });

    return html;
}

/**
 * Generate HTML for a list of test results
 */
function generateTestList(tests: any[]): string {
    if (!tests || tests.length === 0) {
        return '<p>No tests found.</p>';
    }

    let html = '';
    for (const test of tests) {
        const testClass = test.outcome.toLowerCase();
        const testId = `test-${Math.random().toString(36).substr(2, 9)}`;
        const isFailedTest = test.outcome === 'Failed';

        html += `<div class="test-details">
            <details class="vscode-collapsible">
                <summary>
                    <i class="codicon codicon-chevron-right details-icon"></i>
                    <h2 class="title">
                        ${escapeHtmlAll(test.name)}
                    </h2>
                </summary>
                <div style="margin-left:0.5rem; margin-bottom:0.5rem">
                    <div>Class: ${escapeHtmlAll(test.className)}</div>
                    ${test.outcome !== 'NotExecuted' ? `<div>Duration: ${formatDuration(test.duration)}</div>` : ''}
                </div>`;

        if (test.errorInfo) {
            html += `
                <details class="vscode-collapsible sub">
                    <summary>
                        <i class="codicon codicon-chevron-right details-icon"></i>
                        <h2 class="title">
                            <i class="codicon codicon-info section-icon"></i>
                            Error Details
                        </h2>
                    </summary>
                    <div style="margin-left:0.5rem">
                        <div class="error-message">${escapeHtmlPreserveLinks(test.errorInfo.message)}</div>
                        ${test.errorInfo.stackTrace ?
                    `<div class="stack-trace">${escapeHtmlPreserveLinks(test.errorInfo.stackTrace)}</div>` :
                    ''}
                    </div>
                </details>`;
        }

        if (test.output) {
            html += `
                <details class="vscode-collapsible sub">
                    <summary style="margin-bottom:0.5rem">
                        <i class="codicon codicon-chevron-right details-icon"></i>
                        <h2 class="title">
                            <i class="codicon codicon-terminal section-icon"></i>
                            Output
                        </h2>
                    </summary>
                    <div style="margin-left:0.5rem">
                        <div class="test-output">${escapeHtmlPreserveLinks(test.output)}</div>
                    </div>
                </details>`;
        }

        // Render Result Files section
        if (test.resultFiles && test.resultFiles.length > 0) {
            html += `
                <details class="vscode-collapsible sub">
                    <summary style="margin-bottom:0.5rem">
                        <i class="codicon codicon-chevron-right details-icon"></i>
                        <h2 class="title">
                            <i class="codicon codicon-file section-icon"></i>
                            Result Files (${test.resultFiles.length})
                        </h2>
                    </summary>
                    <div class="result-files-container">
                        ${test.resultFiles.map((filePath: string) => {
                const fileName = path.basename(filePath);
                if (isImageFile(filePath)) {
                    const dataUri = readFileAsBase64(filePath);
                    if (dataUri) {
                        return `
                                        <div class="result-file-item result-file-image-item">
                                            <div class="result-file-name">
                                                <i class="codicon codicon-file-media"></i>
                                                ${escapeHtml(fileName)}
                                            </div>
                                            <img src="${dataUri}" alt="${escapeHtml(fileName)}" class="result-file-image" />
                                        </div>`;
                    } else {
                        return `
                                        <div class="result-file-item">
                                            <i class="codicon codicon-file-media"></i>
                                            <span class="result-file-name">${escapeHtml(fileName)}</span>
                                            <span class="result-file-error">(File not found)</span>
                                        </div>`;
                    }
                } else {
                    return `
                                    <div class="result-file-item">
                                        <a href="#" class="result-file-link" data-filepath="${escapeHtml(filePath)}">
                                            <i class="codicon codicon-file"></i>
                                            ${escapeHtml(fileName)}
                                        </a>
                                        <span class="result-file-path">${escapeHtml(filePath)}</span>
                                    </div>`;
                }
            }).join('')}
                    </div>
                </details>`;
        }

        html += `</details></div>`;
    }

    return html;
}

/**
 * Format duration from TRX format to a more readable format
 */
function formatDuration(durationStr: string): string {
    if (!durationStr) { return 'N/A'; }

    // If the duration is in the format "00:00:00.0000000"
    if (/^\d{2}:\d{2}:\d{2}/.test(durationStr)) {
        return durationStr;
    }

    // Otherwise, assume it's in the .NET TimeSpan format
    try {
        // TimeSpan format usually has the form "days.hours:minutes:seconds.fractional"
        // We'll try to parse it to milliseconds
        const matches = durationStr.match(/^(?:(\d+)\.)?(\d{2}):(\d{2}):(\d{2})(?:\.(\d+))?$/);
        if (!matches) { return durationStr; }

        const days = matches[1] ? parseInt(matches[1]) : 0;
        const hours = parseInt(matches[2]) + (days * 24);
        const minutes = parseInt(matches[3]);
        const seconds = parseInt(matches[4]);
        const ms = matches[5] ? parseInt(matches[5].substring(0, 3)) : 0;

        // Format the duration in a readable way
        if (hours > 0) {
            return `${hours}h ${minutes}m ${seconds}.${ms}s`;
        } else if (minutes > 0) {
            return `${minutes}m ${seconds}.${ms}s`;
        } else {
            return `${seconds}.${ms}s`;
        }
    } catch (e) {
        return durationStr;
    }
}

/**
 * Escape HTML special characters
 */
function escapeHtml(text: string): string {
    if (!text) { return ''; }
    return text
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#039;");
}

/**
 * Escape HTML special characters and preserve URLs as clickable links
 */
function escapeHtmlPreserveLinks(text: string): string {
    if (!text) { return ''; }
    // First escape HTML
    const escaped = escapeHtml(text);

    // Then convert URLs to clickable links
    return escaped.replace(
        /(https?:\/\/[^\s<]+|www\.[^\s<]+\.[^\s<]+)/gi,
        (url) => `<a href="${url.startsWith('www.') ? 'http://' + url : url}" target="_blank">${url}</a>`
    );
}

/**
 * Escape HTML special characters and URLs without making them clickable
 */
function escapeHtmlAll(text: string): string {
    if (!text) { return ''; }
    return text
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#039;")
        .replace(/https?:\/\/[^\s<]+|www\.[^\s<]+\.[^\s<]+/gi, (url) => {
            return url.replace(/[:/.]/g, (char) => `&#${char.charCodeAt(0)};`);
        });
}

// Export private functions for testing
// These exports won't be included in the compiled JS unless NODE_ENV=test
if (process.env.NODE_ENV === 'test') {
    // Using 'exports' to add properties to the module's exports object
    // This makes them accessible in tests but keeps them private in normal usage
    Object.defineProperties(exports, {
        'parseTrxContent': {
            value: parseTrxContent,
            configurable: true
        },
        'normalizeTrxData': {
            value: normalizeTrxData,
            configurable: true
        },
        'extractCounters': {
            value: extractCounters,
            configurable: true
        },
        'extractTestDefinitions': {
            value: extractTestDefinitions,
            configurable: true
        },
        'extractTestResults': {
            value: extractTestResults,
            configurable: true
        },
        'linkTestResultsWithDefinitions': {
            value: linkTestResultsWithDefinitions,
            configurable: true
        },
        'formatDate': {
            value: formatDate,
            configurable: true
        },
        'formatDuration': {
            value: formatDuration,
            configurable: true
        },
        'generateHtmlContent': {
            value: generateHtmlContent,
            configurable: true
        },
        'generateTestList': {
            value: generateTestList,
            configurable: true
        },
        'escapeHtml': {
            value: escapeHtml,
            configurable: true
        },
        'escapeHtmlPreserveLinks': {
            value: escapeHtmlPreserveLinks,
            configurable: true
        },
        'escapeHtmlAll': {
            value: escapeHtmlAll,
            configurable: true
        },
        'isImageFile': {
            value: isImageFile,
            configurable: true
        },
        'getImageMimeType': {
            value: getImageMimeType,
            configurable: true
        },
        'readFileAsBase64': {
            value: readFileAsBase64,
            configurable: true
        },
        'resolveResultFilePath': {
            value: resolveResultFilePath,
            configurable: true
        }
    });
}